Fix image format and include graph_nav_util in install (#29)
* install graph_nav_util with catkin_install_python

* fix usage of Image.Format to be consistent with other usages

Using Image.Format.FORMAT_RAW causes an AttributeError:

AttributeError: 'EnumTypeWrapper' object has no attribute 'FORMAT_RAW'

The usage here was inconsistent with usages in other files.